import Head from 'next/head'
import Avatar from '../components/Avatar'
import Image from "next/image";
import { MicrophoneIcon, Squares2X2Icon } from "@heroicons/react/24/solid";
import { MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import Footer from '../components/footer';
import { useRouter } from 'next/router';
import { useRef } from 'react';



export default function Home() {
  const router = useRouter();

  const searchInputRef = useRef(null);

  const search = (e) =>{
    e.preventDefault();
    const term = searchInputRef.current.value;
    if (!term)
      return;

    router.push(`/search?term=${term}`);
  }

  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      {/* header */}
      <header className='flex w-full p-5 justify-between text-sm text-gray-700 '>
        {/* left */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p  className='link'>Store</p>
        </div>

        {/* right */}
        <div className='flex space-x-4 items-center'>
          <p  className='link'>Gmail</p>
          <p  className='link'>Images</p>
        {/* Icon */}
        <Squares2X2Icon className="h-10 w-10 rounded-full p-2 hover:bg-gray-100 cursor-pointer"/>


        {/* Avatar */}
        <Avatar url='https://static01.nyt.com/images/2019/04/16/sports/16onsoccerweb-2/merlin_153612873_5bb119b9-8972-4087-b4fd-371cab8c5ba2-superJumbo.jpg'/>
        </div>



        
        </header>


      {/* body */}
      <form className='flex flex-col items-center mt-44 flex-grow w-4/5 '>
        <Image
          src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          height="100"
          width="300"
          alt="Google"
        />

        <div className='flex w-full mt-5 hover:shadow-lg max-w-md focus-within:shadow-lg rounded-full border border-gray-500 px-5 py-3 item-center sm:max-w-xl lg:max-w-2xl '>
          <MagnifyingGlassIcon className='h-5 mr-3 text-gray-500'/>
          <input 
          ref={searchInputRef}
          type="text" className="flex-grow focus outline-none "/>
          <MicrophoneIcon className='h-5 w-5' />
        </div>
        
        <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row space-x-4 ' >
        <button onClick={search} className='btn'>Google Search</button>

        <button  onClick={search} className='btn'>naskia fiti</button>

        </div>
      </form>


      {/* footer */}
      <Footer/>

    </div>
  )
}
